name: WordPress Plugin CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - name: Check PHP Syntax
        run: find . -type f -name "*.php" -exec php -l {} \;

      - name: WPCS check
        uses: 10up/wpcs-action@stable

      - name: Run PHPUnit
        run: vendor/bin/phpunit || echo "No tests found"

      - name: Build Plugin Zip
        run: |
          mkdir -p build
          zip -r build/my-plugin.zip . -x "*.git*" -x "vendor/*" -x "tests/*" -x ".github/*"
