name: WP Plugin • CI & Release

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*', '*.*.*' ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  lint:
    name: PHPCS Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: phpcs, cs2pr
          extensions: mbstring, intl, json, dom, curl

      - name: Install WordPress Coding Standards
        run: |
          git clone --depth 1 --branch develop https://github.com/WordPress/WordPress-Coding-Standards.git wpcs
          phpcs --config-set installed_paths $(pwd)/wpcs
          phpcs -i

      - name: Run PHPCS with WPCS
        run: |
          phpcs --standard=WordPress --extensions=php --ignore=vendor,node_modules . -q --report=checkstyle | cs2pr

  build-zip:
    name: Build distributable zip
    runs-on: ubuntu-latest
    needs: lint
    if: ${{ github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build plugin zip (respects .distignore if present)
        uses: 10up/action-wordpress-plugin-build-zip@v1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-zip
          path: ./*.zip
          if-no-files-found: error
          retention-days: 7

  github-release:
    name: Attach zip to GitHub Release
    runs-on: ubuntu-latest
    needs: build-zip
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: plugin-zip
          path: ./dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*.zip
          generate_release_notes: true
