name: WordPress Plugin CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - name: Check PHP Syntax
        run: find . -type f -name "*.php" -exec php -l {} \;

      # - name: WPCS check
      #   uses: 10up/wpcs-action@stable

      - name: Run PHPUnit
        run: vendor/bin/phpunit || echo "No tests found"

      - name: Build Plugin Zip
        run: |
          mkdir -p build
          zip -r build/my-plugin.zip . -x "*.git*" -x "vendor/*" -x "tests/*" -x ".github/*"

      - name: Extract version from index.php
        id: get_version
        run: |
          VERSION=$(grep -E "Version:\s*[0-9]+\.[0-9]+(\.[0-9]+)?" index.php | sed -E 's/.*Version:\s*([0-9]+\.[0-9]+(\.[0-9]+)?).*/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if release exists
        id: check_release
        uses: actions/github-script@v7
        with:
          script: |
            const version = core.getInput('version');
            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const exists = releases.find(r => r.tag_name === `v${version}`);
            core.setOutput("exists", exists ? "true" : "false");
          result-encoding: string
        env:
          version: ${{ steps.get_version.outputs.version }}

      - name: Create GitHub Release
        if: steps.check_release.outputs.exists == 'false'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          files: build/my-plugin.zip
