  lint:
    name: PHPCS Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: phpcs, cs2pr
          extensions: mbstring, intl, json, dom, curl

      - name: Install WordPress Coding Standards
        run: |
          git clone --depth 1 --branch develop https://github.com/WordPress/WordPress-Coding-Standards.git wpcs
          phpcs --config-set installed_paths $(pwd)/wpcs
          phpcs -i

      - name: Run PHPCS with WPCS
        run: |
          phpcs --standard=WordPress --extensions=php --ignore=vendor,node_modules . -q --report=checkstyle | cs2pr
